services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
      APACHE_LOG_DIR: /var/log/apache2
      APACHE_RUN_DIR: /var/run/apache2
      APACHE_LOCK_DIR: /var/lock/apache2
      PHP_ROOT_DIR: /var/www/html
      # Variables depuis fichier .env en prod
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    working_dir: /var/www/html
    networks:
      - app-network

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network

volumes:
  db_data:
    driver: local

networks:
  app-network:
    driver: bridge